name: deploy-prod

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out branch
        uses: actions/checkout@v2
      - name: Setting up node with version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: create env file
        run: |
          echo REACT_APP_TEST="test" >> .env
      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
      - name: Deploy the static site to the S3 buckets
        run: aws s3 sync ./dist/ s3://www.hvorstort.dk --delete --exclude "index.html"
      - name: Upload index.html with no-cache
        run: aws s3 cp ./dist/index.html s3://www.hvorstort.dk/index.html --cache-control "no-cache"
      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id=E1ED5R0KMNKIZR --paths "/*"
